### ISSUE TITLE
constrainedClustering module not found

### ISSUE THREAD

**Issue by kratos6753** [ashkanmradi/constrained-k-means#1]
I have not found the modules `constrainedClustering` used in the repository. I would appreciate if you help me with that. Thanks.

**Comment by ashkanmradi** [comment]
Hello @kratos6753 
The constraints were defined in [generateConstraints.py](https://github.com/ashkanmradi/constrained-k-means/blob/master/codes/generateConstraints.py) file. 
if you need to generate the constraints based on active learning methods, you also need to run [ExploreConsolidate.py](https://github.com/ashkanmradi/constrained-k-means/blob/master/codes/ExploreConsolidate.py) and [Oracle.py](https://github.com/ashkanmradi/constrained-k-means/blob/master/codes/Oracle.py) in order to generate constraints. 
we also implement [PC_Kmeans.py](https://github.com/ashkanmradi/constrained-k-means/blob/master/codes/PC_Kmeans.py) and [COP-Kmeans.py](https://github.com/ashkanmradi/constrained-k-means/blob/master/codes/COP_Kmeans.py) which get the constraints as their argument and do the clustering process based on the generated constraints. 
Finally, [Main.py](https://github.com/ashkanmradi/constrained-k-means/blob/master/codes/Main.py) uses all these files to run the algorithms and generate the results.
